//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "7e7c626662173519")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Forside</summary>
	[PublishedContentModel("forside")]
	public partial class Forside : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "forside";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Forside(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Forside, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Burgermenu: Burgermenu ikon til mobil
		///</summary>
		[ImplementPropertyType("burgermenu")]
		public IPublishedContent Burgermenu
		{
			get { return this.GetPropertyValue<IPublishedContent>("burgermenu"); }
		}

		///<summary>
		/// Facebook: Facebook ikon
		///</summary>
		[ImplementPropertyType("facebook")]
		public IPublishedContent Facebook
		{
			get { return this.GetPropertyValue<IPublishedContent>("facebook"); }
		}

		///<summary>
		/// Forside overskrift: Overskrift på forside
		///</summary>
		[ImplementPropertyType("forsideOverskrift")]
		public string ForsideOverskrift
		{
			get { return this.GetPropertyValue<string>("forsideOverskrift"); }
		}

		///<summary>
		/// Forside tekst: Tekst til forsiden
		///</summary>
		[ImplementPropertyType("forsideTekst")]
		public string ForsideTekst
		{
			get { return this.GetPropertyValue<string>("forsideTekst"); }
		}

		///<summary>
		/// Header logo: Logo
		///</summary>
		[ImplementPropertyType("headerLogo")]
		public IPublishedContent HeaderLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("headerLogo"); }
		}

		///<summary>
		/// Hero 1024px: Hero billede 1024px
		///</summary>
		[ImplementPropertyType("hero1024px")]
		public IPublishedContent Hero1024px
		{
			get { return this.GetPropertyValue<IPublishedContent>("hero1024px"); }
		}

		///<summary>
		/// Hero 1280px: Hero billede 1280px
		///</summary>
		[ImplementPropertyType("hero1280px")]
		public IPublishedContent Hero1280px
		{
			get { return this.GetPropertyValue<IPublishedContent>("hero1280px"); }
		}

		///<summary>
		/// Hero 1440px: Hero billede 1440px
		///</summary>
		[ImplementPropertyType("hero1440px")]
		public IPublishedContent Hero1440px
		{
			get { return this.GetPropertyValue<IPublishedContent>("hero1440px"); }
		}

		///<summary>
		/// Hero 1536px: Hero billede 1536px
		///</summary>
		[ImplementPropertyType("hero1536px")]
		public IPublishedContent Hero1536px
		{
			get { return this.GetPropertyValue<IPublishedContent>("hero1536px"); }
		}

		///<summary>
		/// Hero  1920px: Hero billede 1920px
		///</summary>
		[ImplementPropertyType("hero1920px")]
		public IPublishedContent Hero1920px
		{
			get { return this.GetPropertyValue<IPublishedContent>("hero1920px"); }
		}

		///<summary>
		/// Hero 375px: Hero billede i 375px
		///</summary>
		[ImplementPropertyType("hero375px")]
		public IPublishedContent Hero375px
		{
			get { return this.GetPropertyValue<IPublishedContent>("hero375px"); }
		}

		///<summary>
		/// Hero 627px: Hero billede 627px
		///</summary>
		[ImplementPropertyType("hero627px")]
		public IPublishedContent Hero627px
		{
			get { return this.GetPropertyValue<IPublishedContent>("hero627px"); }
		}

		///<summary>
		/// Hero 768px: Hero billede 768px
		///</summary>
		[ImplementPropertyType("hero768px")]
		public IPublishedContent Hero768px
		{
			get { return this.GetPropertyValue<IPublishedContent>("hero768px"); }
		}

		///<summary>
		/// Instagram: Instagram ikon
		///</summary>
		[ImplementPropertyType("instagram")]
		public IPublishedContent Instagram
		{
			get { return this.GetPropertyValue<IPublishedContent>("instagram"); }
		}

		///<summary>
		/// Kagens dag billede: Billede til kagens dag
		///</summary>
		[ImplementPropertyType("kagensDagBillede")]
		public IPublishedContent KagensDagBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("kagensDagBillede"); }
		}

		///<summary>
		/// Kagens dag overskrift: Overskrift til kagens dag
		///</summary>
		[ImplementPropertyType("kagensDagOverskrift")]
		public string KagensDagOverskrift
		{
			get { return this.GetPropertyValue<string>("kagensDagOverskrift"); }
		}

		///<summary>
		/// Kagens dag tekst: Tekst til kagens dag
		///</summary>
		[ImplementPropertyType("kagensDagTekst")]
		public string KagensDagTekst
		{
			get { return this.GetPropertyValue<string>("kagensDagTekst"); }
		}

		///<summary>
		/// Kryds: Kryds til at lukke navigation i mobil
		///</summary>
		[ImplementPropertyType("kryds")]
		public IPublishedContent Kryds
		{
			get { return this.GetPropertyValue<IPublishedContent>("kryds"); }
		}

		///<summary>
		/// Smiley: Smiley rapport
		///</summary>
		[ImplementPropertyType("smiley")]
		public IPublishedContent Smiley
		{
			get { return this.GetPropertyValue<IPublishedContent>("smiley"); }
		}

		///<summary>
		/// tids billede: Billedet til højtid/årstid
		///</summary>
		[ImplementPropertyType("tidsBillede")]
		public IPublishedContent TidsBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("tidsBillede"); }
		}

		///<summary>
		/// Tids overskrift: Overskrif til højtid/årstid
		///</summary>
		[ImplementPropertyType("tidsOverskrift")]
		public string TidsOverskrift
		{
			get { return this.GetPropertyValue<string>("tidsOverskrift"); }
		}

		///<summary>
		/// Tids tekst: Tekst til højtid/årstid
		///</summary>
		[ImplementPropertyType("tidsTekst")]
		public string TidsTekst
		{
			get { return this.GetPropertyValue<string>("tidsTekst"); }
		}
	}

	/// <summary>Brød</summary>
	[PublishedContentModel("broed")]
	public partial class Broed : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "broed";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Broed(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Broed, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// B hero 1024px: Hero billede 1024px
		///</summary>
		[ImplementPropertyType("bHero1024px")]
		public IPublishedContent BHero1024px
		{
			get { return this.GetPropertyValue<IPublishedContent>("bHero1024px"); }
		}

		///<summary>
		/// B hero 1280px: Hero billede 1280px
		///</summary>
		[ImplementPropertyType("bHero1280px")]
		public IPublishedContent BHero1280px
		{
			get { return this.GetPropertyValue<IPublishedContent>("bHero1280px"); }
		}

		///<summary>
		/// B hero 1440px: Hero billede 1440px
		///</summary>
		[ImplementPropertyType("bHero1440px")]
		public IPublishedContent BHero1440px
		{
			get { return this.GetPropertyValue<IPublishedContent>("bHero1440px"); }
		}

		///<summary>
		/// B hero 1536px: Hero billede 1536px
		///</summary>
		[ImplementPropertyType("bHero1536px")]
		public IPublishedContent BHero1536px
		{
			get { return this.GetPropertyValue<IPublishedContent>("bHero1536px"); }
		}

		///<summary>
		/// B hero 1920px: Hero billede 1920px
		///</summary>
		[ImplementPropertyType("bHero1920px")]
		public IPublishedContent BHero1920px
		{
			get { return this.GetPropertyValue<IPublishedContent>("bHero1920px"); }
		}

		///<summary>
		/// B hero 375px: Hero billede 375px
		///</summary>
		[ImplementPropertyType("bHero375px")]
		public IPublishedContent BHero375px
		{
			get { return this.GetPropertyValue<IPublishedContent>("bHero375px"); }
		}

		///<summary>
		/// B hero 627px: Hero billede 627px
		///</summary>
		[ImplementPropertyType("bHero627px")]
		public IPublishedContent BHero627px
		{
			get { return this.GetPropertyValue<IPublishedContent>("bHero627px"); }
		}

		///<summary>
		/// B hero 768px: Hero billede 768px
		///</summary>
		[ImplementPropertyType("bHero768px")]
		public IPublishedContent BHero768px
		{
			get { return this.GetPropertyValue<IPublishedContent>("bHero768px"); }
		}

		///<summary>
		/// Boller billede: Billede til boller sektionen
		///</summary>
		[ImplementPropertyType("bollerBillede")]
		public IPublishedContent BollerBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("bollerBillede"); }
		}

		///<summary>
		/// Boller sektion overskrift: boller sektionens overskrift
		///</summary>
		[ImplementPropertyType("bollerSektionOverskrift")]
		public string BollerSektionOverskrift
		{
			get { return this.GetPropertyValue<string>("bollerSektionOverskrift"); }
		}

		///<summary>
		/// Boller sektion tekst: Teksten til boller sektionen
		///</summary>
		[ImplementPropertyType("bollerSektionTekst")]
		public string BollerSektionTekst
		{
			get { return this.GetPropertyValue<string>("bollerSektionTekst"); }
		}

		///<summary>
		/// Brød billede: Billede til brød sektion
		///</summary>
		[ImplementPropertyType("broedBillede")]
		public IPublishedContent BroedBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("broedBillede"); }
		}

		///<summary>
		/// Brød overskrift: Overskrift til øverste sektion på brød
		///</summary>
		[ImplementPropertyType("broedOverskrift")]
		public string BroedOverskrift
		{
			get { return this.GetPropertyValue<string>("broedOverskrift"); }
		}

		///<summary>
		/// Brød sektion overskrift: Brød sektionen
		///</summary>
		[ImplementPropertyType("broedSektionOverskrift")]
		public string BroedSektionOverskrift
		{
			get { return this.GetPropertyValue<string>("broedSektionOverskrift"); }
		}

		///<summary>
		/// Brød sektion tekst: teksten til brød sektion
		///</summary>
		[ImplementPropertyType("broedSektionTekst")]
		public string BroedSektionTekst
		{
			get { return this.GetPropertyValue<string>("broedSektionTekst"); }
		}

		///<summary>
		/// Brød tekst: Tekst til øverste sektion
		///</summary>
		[ImplementPropertyType("broedTekst")]
		public string BroedTekst
		{
			get { return this.GetPropertyValue<string>("broedTekst"); }
		}

		///<summary>
		/// Burgermenu
		///</summary>
		[ImplementPropertyType("burgermenu")]
		public IPublishedContent Burgermenu
		{
			get { return this.GetPropertyValue<IPublishedContent>("burgermenu"); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public IPublishedContent Facebook
		{
			get { return this.GetPropertyValue<IPublishedContent>("facebook"); }
		}

		///<summary>
		/// Flute billede: Billede til flute sektionen
		///</summary>
		[ImplementPropertyType("fluteBillede")]
		public IPublishedContent FluteBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("fluteBillede"); }
		}

		///<summary>
		/// Flute sektion overskrift: Flute sektionens overskrift
		///</summary>
		[ImplementPropertyType("fluteSektionOverskrift")]
		public string FluteSektionOverskrift
		{
			get { return this.GetPropertyValue<string>("fluteSektionOverskrift"); }
		}

		///<summary>
		/// Flute sektion tekst: Teksten til flute sektionen
		///</summary>
		[ImplementPropertyType("fluteSektionTekst")]
		public string FluteSektionTekst
		{
			get { return this.GetPropertyValue<string>("fluteSektionTekst"); }
		}

		///<summary>
		/// Header logo
		///</summary>
		[ImplementPropertyType("headerLogo")]
		public IPublishedContent HeaderLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("headerLogo"); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("instagram")]
		public IPublishedContent Instagram
		{
			get { return this.GetPropertyValue<IPublishedContent>("instagram"); }
		}

		///<summary>
		/// Kryds
		///</summary>
		[ImplementPropertyType("kryds")]
		public IPublishedContent Kryds
		{
			get { return this.GetPropertyValue<IPublishedContent>("kryds"); }
		}

		///<summary>
		/// Rugbrød billede: Billede til rugbrød sektionen
		///</summary>
		[ImplementPropertyType("rugbroedBillede")]
		public IPublishedContent RugbroedBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("rugbroedBillede"); }
		}

		///<summary>
		/// Rugbrød sektion overskrift: Rugbrød sektionens overskrift
		///</summary>
		[ImplementPropertyType("rugbroedSektionOverskrift")]
		public string RugbroedSektionOverskrift
		{
			get { return this.GetPropertyValue<string>("rugbroedSektionOverskrift"); }
		}

		///<summary>
		/// Rugbrød sektion tekst: Teksten til rugbrød sektionen
		///</summary>
		[ImplementPropertyType("rugbroedSektionTekst")]
		public string RugbroedSektionTekst
		{
			get { return this.GetPropertyValue<string>("rugbroedSektionTekst"); }
		}

		///<summary>
		/// Smiley
		///</summary>
		[ImplementPropertyType("smiley")]
		public IPublishedContent Smiley
		{
			get { return this.GetPropertyValue<IPublishedContent>("smiley"); }
		}
	}

	/// <summary>Kager</summary>
	[PublishedContentModel("kager")]
	public partial class Kager : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "kager";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Kager(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Kager, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Burgermenu: Burgermenu ikon
		///</summary>
		[ImplementPropertyType("burgermenu")]
		public IPublishedContent Burgermenu
		{
			get { return this.GetPropertyValue<IPublishedContent>("burgermenu"); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public IPublishedContent Facebook
		{
			get { return this.GetPropertyValue<IPublishedContent>("facebook"); }
		}

		///<summary>
		/// Flødeskumskager billede: Billede til flødeskumskager
		///</summary>
		[ImplementPropertyType("floedeskumskagerBillede")]
		public IPublishedContent FloedeskumskagerBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("floedeskumskagerBillede"); }
		}

		///<summary>
		/// Flødeskumskager overskrift: Overskriv til flødeskumskager
		///</summary>
		[ImplementPropertyType("floedeskumskagerOverskrift")]
		public string FloedeskumskagerOverskrift
		{
			get { return this.GetPropertyValue<string>("floedeskumskagerOverskrift"); }
		}

		///<summary>
		/// Flødeskumskager tekst: Tekst til flødeskumskager
		///</summary>
		[ImplementPropertyType("floedeskumskagerTekst")]
		public string FloedeskumskagerTekst
		{
			get { return this.GetPropertyValue<string>("floedeskumskagerTekst"); }
		}

		///<summary>
		/// Header logo
		///</summary>
		[ImplementPropertyType("headerLogo")]
		public IPublishedContent HeaderLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("headerLogo"); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("instagram")]
		public IPublishedContent Instagram
		{
			get { return this.GetPropertyValue<IPublishedContent>("instagram"); }
		}

		///<summary>
		/// Kager overskrift: Overskrift til øverste sektion
		///</summary>
		[ImplementPropertyType("kagerOverskrift")]
		public string KagerOverskrift
		{
			get { return this.GetPropertyValue<string>("kagerOverskrift"); }
		}

		///<summary>
		/// Kager tekst: Tekst til øverste sektion
		///</summary>
		[ImplementPropertyType("kagerTekst")]
		public string KagerTekst
		{
			get { return this.GetPropertyValue<string>("kagerTekst"); }
		}

		///<summary>
		/// K hero 1024px
		///</summary>
		[ImplementPropertyType("kHero1024px")]
		public IPublishedContent KHero1024px
		{
			get { return this.GetPropertyValue<IPublishedContent>("kHero1024px"); }
		}

		///<summary>
		/// K hero 1280px: Hero billede 1280px
		///</summary>
		[ImplementPropertyType("kHero1280px")]
		public IPublishedContent KHero1280px
		{
			get { return this.GetPropertyValue<IPublishedContent>("kHero1280px"); }
		}

		///<summary>
		/// K hero 1440px: Hero billede 1440px
		///</summary>
		[ImplementPropertyType("kHero1440px")]
		public IPublishedContent KHero1440px
		{
			get { return this.GetPropertyValue<IPublishedContent>("kHero1440px"); }
		}

		///<summary>
		/// K hero 1536px: Hero billede 1536px
		///</summary>
		[ImplementPropertyType("kHero1536px")]
		public IPublishedContent KHero1536px
		{
			get { return this.GetPropertyValue<IPublishedContent>("kHero1536px"); }
		}

		///<summary>
		/// K hero 1920px: Hero billede 1920px
		///</summary>
		[ImplementPropertyType("kHero1920px")]
		public IPublishedContent KHero1920px
		{
			get { return this.GetPropertyValue<IPublishedContent>("kHero1920px"); }
		}

		///<summary>
		/// K hero 375px: Hero billede 375px
		///</summary>
		[ImplementPropertyType("kHero375px")]
		public IPublishedContent KHero375px
		{
			get { return this.GetPropertyValue<IPublishedContent>("kHero375px"); }
		}

		///<summary>
		/// K hero 627px: Hero billede 627px
		///</summary>
		[ImplementPropertyType("kHero627px")]
		public IPublishedContent KHero627px
		{
			get { return this.GetPropertyValue<IPublishedContent>("kHero627px"); }
		}

		///<summary>
		/// K hero 768px: Hero billede 768px
		///</summary>
		[ImplementPropertyType("kHero768px")]
		public IPublishedContent KHero768px
		{
			get { return this.GetPropertyValue<IPublishedContent>("kHero768px"); }
		}

		///<summary>
		/// Kryds: Kryds til at lukke navigationen på mobil
		///</summary>
		[ImplementPropertyType("kryds")]
		public IPublishedContent Kryds
		{
			get { return this.GetPropertyValue<IPublishedContent>("kryds"); }
		}

		///<summary>
		/// Smiley
		///</summary>
		[ImplementPropertyType("smiley")]
		public IPublishedContent Smiley
		{
			get { return this.GetPropertyValue<IPublishedContent>("smiley"); }
		}

		///<summary>
		/// Tærter billede: Billede til tærter
		///</summary>
		[ImplementPropertyType("taerterBillede")]
		public IPublishedContent TaerterBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("taerterBillede"); }
		}

		///<summary>
		/// Tærter overskrift: Overskrift til tærter
		///</summary>
		[ImplementPropertyType("taerterOverskrift")]
		public string TaerterOverskrift
		{
			get { return this.GetPropertyValue<string>("taerterOverskrift"); }
		}

		///<summary>
		/// Tærter tekst: Tekst til tærter
		///</summary>
		[ImplementPropertyType("taerterTekst")]
		public string TaerterTekst
		{
			get { return this.GetPropertyValue<string>("taerterTekst"); }
		}

		///<summary>
		/// Tørkager billede: Billede til tørkager
		///</summary>
		[ImplementPropertyType("toerkagerBillede")]
		public IPublishedContent ToerkagerBillede
		{
			get { return this.GetPropertyValue<IPublishedContent>("toerkagerBillede"); }
		}

		///<summary>
		/// Tørkager overskrift: Overskrift til tørkager
		///</summary>
		[ImplementPropertyType("toerkagerOverskrift")]
		public string ToerkagerOverskrift
		{
			get { return this.GetPropertyValue<string>("toerkagerOverskrift"); }
		}

		///<summary>
		/// Tørkager tekst: Tekst til tørkager
		///</summary>
		[ImplementPropertyType("toerkagerTekst")]
		public string ToerkagerTekst
		{
			get { return this.GetPropertyValue<string>("toerkagerTekst"); }
		}
	}

	/// <summary>Fristelser</summary>
	[PublishedContentModel("fristelser")]
	public partial class Fristelser : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fristelser";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Fristelser(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Fristelser, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Bestillingskager</summary>
	[PublishedContentModel("bestillingskager")]
	public partial class Bestillingskager : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "bestillingskager";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Bestillingskager(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Bestillingskager, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Vores historie</summary>
	[PublishedContentModel("voresHistorie")]
	public partial class VoresHistorie : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "voresHistorie";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public VoresHistorie(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VoresHistorie, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Kontakt os</summary>
	[PublishedContentModel("kontaktOs")]
	public partial class KontaktOs : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "kontaktOs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public KontaktOs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<KontaktOs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
